package com.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName = "InputDataTable")
public class Input {
    private String first_name;
    private String id;
    private String last_name;
    private String job_title;
    private String from_source;
    private String to_source;

        

    public Input() {
    }


    public Input(String first_name, String last_name, String job_title, String from_source, String to_source) {
        this.first_name = first_name;
        this.last_name = last_name;
        this.job_title = job_title;
        this.from_source = from_source;
        this.to_source = to_source;
    }


    public Input(String first_name, String id, String last_name, String job_title, String from_source, String to_source) {
        this.first_name = first_name;
        this.id = id;
        this.last_name = last_name;
        this.job_title = job_title;
        this.from_source = from_source;
        this.to_source = to_source;
    }


    
    @DynamoDBHashKey(attributeName="first_name")
    public String getFirst_name() {
        return first_name;
    }


    public void setFirst_name(String first_name) {
        this.first_name = first_name;
    }

    @DynamoDBAttribute(attributeName="last_name")
    public String getLast_name() {
        return last_name;
    }


    public void setLast_name(String last_name) {
        this.last_name = last_name;
    }

    @DynamoDBAttribute(attributeName="job_title")
    public String getJob_title() {
        return job_title;
    }


    public void setJob_title(String job_title) {
        this.job_title = job_title;
    }

    @DynamoDBAttribute(attributeName="from_source")
    public String getFrom_source() {
        return from_source;
    }


    public void setFrom_source(String from_source) {
        this.from_source = from_source;
    }

    @DynamoDBAttribute(attributeName="to_source")
    public String getTo_source() {
        return to_source;
    }


    public void setTo_source(String to_source) {
        this.to_source = to_source;
    }


    @DynamoDBRangeKey(attributeName="id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }



    @Override
    public String toString() {
        if (id!=null){
            return "Input [first_name=" + first_name + ", id=" + id + ", last_name=" + last_name + ", job_title="
                + job_title + ", from_source=" + from_source + ", to_source=" + to_source + "]";
        }
        return "Input [first_name=" + first_name + ", last_name=" + last_name + ", job_title="
                + job_title + ", from_source=" + from_source + ", to_source=" + to_source + "]";
    }   
 
}
